app:
  logo: "http://marcosbenitez.ar/rutapp/logo_chico.png"
---
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/rutapp_db'
    username: "grupo2"
    password: grupo2
    #username: "urutapp"
    #password: Urut4pp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    properties:
      hibernate.format_sql: true
#logging:
 # level:
  #  org:
   #   hibernate:
    #    type: trace
        
        